language: objective-c
osx_image: xcode8.3

env:
  global:
    - DESTINATION="platform=iOS Simulator,name=iPhone 7"

before_install:
  - export IOS_SIMULATOR_UDID=$(instruments -s devices | grep "$ios_device ($ios_version)" | sed -E 's/.*\[([0-9A-F-]+)\].*/\1/g')
  - echo "Prelaunching iOS simulator $IOS_SIMULATOR_UDID"
  - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID

script:
  - set -o pipefail
  - xcodebuild build-for-testing test-without-building -workspace i18nSwift.xcworkspace -scheme i18nSwift -configuration Release -sdk iphonesimulator -destination "$DESTINATION" -enableCodeCoverage YES
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
